### ISSUE TITLE
关于θ旋转角度

### ISSUE THREAD

**Issue by Chrispaoge** [fengkaibit/UAV-ROD#3]
感谢你的工作，数据集里的θ都非常的小，想请问一下旋转角度θ的大小具体是以哪个为参照以及θ的取值范围是多少，感谢

**Comment by fengkaibit** [comment]
感谢你的提问。角度按照弧度标注，范围为[0, 2pi），所以数值上看着比较小。车辆标注角度以车头方向作为基准方向，并按顺时针方向增加。

**Comment by Chrispaoge** [comment]
好的，懂了，3q
